export default {
  STRING: "STRING",
  STRING_MULTI_LINE: "STRING_MULTI_LINE",
  NUMBER: "NUMBER",
  DATE: "DATE",
  TIME: "TIME",
  DATE_TIME: "DATE_TIME",
  BOOL: "BOOL",
  RICH_TEXT: "RICH_TEXT",
  ARRAY: "ARRAY",
  URL: "URL",
  EMAIL: "EMAIL",
  THEME: "THEME",
}